# Generated by Django 3.2.12 on 2023-03-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emotion',
            field=models.CharField(blank=True, choices=[('VeryGood', 'Verygood'), ('Good', 'Good'), ('Soso', 'Soso'), ('Bad', 'Bad'), ('VeryBad', 'Verybad')], max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='weather',
            field=models.CharField(blank=True, choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy'), ('Foggy', 'Foggy'), ('Snowy', 'Snowy'), ('Cloudy', 'Cloudy'), ('Stormy', 'Stormy')], max_length=10),
        ),
    ]
