# Generated by Django 3.2.12 on 2023-03-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230329_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check_img',
            field=models.BooleanField(default=False),
        ),
    ]
